apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: madhan1
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32074

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: madhan1
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: madhanrs14/nginx:v2
        ports:
        - containerPort: 80
